### ISSUE TITLE
MVS explorer editor can not be displayed becuase of "TypeError: Cannot read property 'setContents' of null"

### ISSUE THREAD

**Issue by LiangXuehongBJ** [zowe/explorer-mvs#5] opened 2018-09-14 06:14 UTC
[
<img width="1347" alt="screen shot 2018-09-13 at 3 19 59 pm" src="https://user-images.githubusercontent.com/26133671/45532880-3f007f80-b828-11e8-96bc-97e40abf63ba.png">
<img width="903" alt="screen shot 2018-09-13 at 3 21 18 pm" src="https://user-images.githubusercontent.com/26133671/45532884-3f991600-b828-11e8-833d-ab68d91f8e45.png">
<img width="985" alt="screen shot 2018-09-13 at 3 21 30 pm" src="https://user-images.githubusercontent.com/26133671/45532886-3f991600-b828-11e8-9a77-ad2a5db66c11.png">

MVS explorer editor could not show content because of an exception often.
 
Sometimes it works fine, sometimes it does not.
 
It can be reproduced easily with zowe 0.8.3 or 0.9.0.
 
Could you please help to take a look at this issue?
 
Thank you very much!

**Comment by jordanCain** [comment] 2018-09-26 10:27
This is likely due to a race condition where we try to set the content of the editor before the editor has been initialised. I'll take a look into adding logic to prevent the requesting of content until after the editor has been initialised.

**Comment by LiangXuehongBJ** [comment] 2018-10-23 08:35
Hi, Jordan.
Will this issue be fixed in Zowe 0.9.3 release?
Thank you very much!

**Comment by jordanCain** [comment] 2018-10-23 08:38
@LiangXuehongBJ A fix for this went in, https://github.com/zowe/explorer-mvs/pull/13 just awaiting validation

**Comment by jordanCain** [comment] 2018-10-29 13:36
@LiangXuehongBJ Im no longer able to reproduce this in 0.9.2 therefore I will mark this issue as closed. If you are able to reproduce this feel free to re open this issue

**Comment by LiangXuehongBJ** [comment] 2018-11-06 02:13
@jordanCain  I can reproduce this issue in 0.9.2 now.

Here are logs in console.log:
VM806 app.min.js:1025  action RECEIVE_CONTENT @ 10:11:05.183
VM809 app.min.js:1025  action REQUEST_CONTENT @ 10:11:05.874
VM809 app.min.js:1025  action RECEIVE_CONTENT @ 10:11:06.158
app.min.js:1025  action REQUEST_CONTENT @ 10:12:32.524
app.min.js:1025  action RECEIVE_CONTENT @ 10:12:32.840
app.min.js:1025  action PUSH_NOTIFICATION_MESSAGE @ 10:12:32.853
app.min.js:1025  action INVALIDATE_CONTENT @ 10:12:32.860
app.min.js:1025  action POP_NOTIFICATION_MESSAGE @ 10:12:36.858

**Comment by LiangXuehongBJ** [comment] 2018-11-06 02:52
<img width="1017" alt="screen shot 2018-11-06 at 10 48 10 am" src="https://user-images.githubusercontent.com/26133671/48039960-050d8300-e1b2-11e8-960c-37863584de04.png">

**Comment by jordanCain** [comment] 2018-11-21 15:10
fix #29 has been validated and therefore this issue is resolved

**Closed by jordanCain** 2018-11-21 15:10 UTC
